
version: 2

sources:
    - name: kranio_data_lab_ingestion
      description: "dataset of ingestion"
      tables:
        - name : ventes
          description: ventes
        - name : produits
          description : produits
        - name : stocks
          description: stocks
        - name : clients
          description : clients
        
