name: Deploy

on:
  push:
    branches:
      - feat/backup
#      - master
#      - development
#  pull_request:
#    branches:
#      - master
#      - development
#
jobs:

  deploy:
    runs-on: ubuntu-latest
#    env: 
#      envir: steph-dev
#
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install importlib-metadata==4.8.3 types-pkg-resources==0.1.3
      
      #- name: Display custom environment variables
      #  run: echo ${{ env.envi }}

      - name: zip
        run: python3 ./infraestructure/__cicd__/conversion_to_zip_file.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: get_parameters.zip
          path: terraform/cloud-functions-files/get_parameters.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: check_dataproc-status.zip
          path: terraform/cloud-functions-files/check_dataproc-status.zip


      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: check_dataproc-status.zip
          path: cloud-functions-files/get_parameters.zip
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: check_dataproc-status.zip
          path: cloud-functions-files/check_dataproc-status.zip

      - name: Debug - Check current directory
        run: pwd

      - name: Debug - List all files
        run: ls -lR  

      - name: Debug - Check file existence
        run: ls -lR terraform/cloud-functions-files/check_dataproc-status.zip 

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > $HOME/kranio-data-lab-b46e531119a7.json

      #- name: Fix JSON Formatting
      #  run: echo '${{ secrets.GCP_CREDENTIALS }}' | tr -d '\\' | sed 's/n/\n/g' > $HOME/kranio-data-lab-b46e531119a7.json

      - name: Export Google Credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/kranio-data-lab-b46e531119a7.json" >> $GITHUB_ENV

      - name: Check environment variable
        run: echo $GOOGLE_APPLICATION_CREDENTIALS 

      - name: Verify credentials file
        run: ls -lah $HOME && cat $HOME/kranio-data-lab-b46e531119a7.json | head -n 5

      - name: Validate JSON
        run: cat $HOME/kranio-data-lab-b46e531119a7.json | jq .

      - name: Terraform Init
        working-directory: 'infraestructure/terraform'
        run: terraform init    

      - name: Terraform Plan 
        working-directory: 'infraestructure/terraform'
        run: terraform plan 

      #- name: Terraform Destroy
      #  working-directory: 'infraestructure/terraform'
      #  run: terraform destroy -auto-approve -input=false

      - name: Terraform Apply
        working-directory: 'infraestructure/terraform'
        run: terraform apply -auto-approve -input=false
 